service: go-advanced-shapes
frameworkVersion: '>=1.28.8'
provider:
  name: aws
  runtime: go1.x
  region: 'us-east-1'
  stage: ${opt:stage}
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::uala-arg-labssupport-local/*'
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: '*'
functions:
  api:
    handler: build/main
    events:
      - http:
          path: /read
          method: POST
      - http:
          path: /create
          method: POST
package:
  patterns:
    - '!*/**'
    - build/main